# Generated by Django 3.0.8 on 2021-08-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='customization',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
