# Generated by Django 3.0.8 on 2021-08-18 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_orderitem_customization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='customization',
        ),
        migrations.CreateModel(
            name='Customization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customization', models.TextField(blank=True, max_length=1000, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Customer')),
            ],
        ),
    ]
