# Generated by Django 3.0.8 on 2021-08-26 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_customer_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customization',
            name='productname',
        ),
        migrations.AddField(
            model_name='customization',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Product'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='1.jpg', null=True, upload_to=''),
        ),
    ]
