# Generated by Django 3.0.8 on 2021-08-26 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20210826_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customization',
            name='product',
        ),
        migrations.AddField(
            model_name='customization',
            name='productname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
