# Generated by Django 3.0.8 on 2021-08-26 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20210826_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customization',
            name='productname',
        ),
        migrations.AddField(
            model_name='customization',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Product'),
        ),
    ]
